apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mintemir/beckend:1.0.0
        env:
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: host
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: user
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: dbname
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
        ports:
        - containerPort: 3000
