apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kurbanaliev.mintemir@gmail.com
    privateKeySecretRef:
      name: lunara
    solvers:
    - http01:
        ingress:
          class: nginx

---

apiVersion: cert-manager.io/v1 
kind: Certificate 
metadata: 
 name: min-crt
spec: 
 secretName: tls-secret
 isCA: true 
 issuerRef: 
   name: letsencrypt-staging
   kind: Issuer 

 dnsNames: 
 - "myvivi.tk"