apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmlunara.fullname" . }}-backend
  labels:
  {{- include "helmlunara.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.type }}
  selector:
    app: backend
  {{- include "helmlunara.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backend.ports | toYaml | nindent 2 -}}