apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helmlunara.fullname" . }}-ingress
  labels:
  {{- include "helmlunara.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: myvivi.tk
    http:
      paths:
      - backend:
          service:
            name: '{{ include "helmlunara.fullname" . }}-frontend'
            port:
              number: 80
        path: /?(.*)
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "helmlunara.fullname" . }}-backend'
            port:
              number: 3000
        path: /api/?(.*)
        pathType: Prefix
  tls:
  - hosts:
    - myvivi.tk
    secretName: tls-secret