apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helmlunara.fullname" . }}-mysecret
  labels:
  {{- include "helmlunara.labels" . | nindent 4 }}
data:
  dbname: {{ required "mysecret.dbname is required" .Values.mysecret.dbname | b64enc
    | quote }}
  host: {{ required "mysecret.host is required" .Values.mysecret.host | b64enc |
    quote }}
  password: {{ required "mysecret.password is required" .Values.mysecret.password
    | b64enc | quote }}
  user: {{ required "mysecret.user is required" .Values.mysecret.user | b64enc |
    quote }}
type: Opaque